language: ruby
rvm:
- 2.4.1

cache: bundler
cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

before_install:
  - set -e
  - if [ "${TRAVIS_TAG?}" ]; then
      AWS_BUCKET="blog.datacite.org";
      ARCHIVE_BUCKET="archive.datacite.org";
      RACK_ENV="production";
      cp .env.master .env;
    elif [ "$TRAVIS_BRANCH" == "master" ]; then
      AWS_BUCKET="blog.test.datacite.org";
      ARCHIVE_BUCKET="archive.test.datacite.org";
      RACK_ENV="stage";
      cp .env.stage .env;
    else
      exit 1;
    fi

  - wget https://github.com/jgm/pandoc/releases/download/1.15.2/pandoc-1.15.2-1-amd64.deb
  - sudo dpkg -i pandoc-1.15.2-1-amd64.deb
  - rm pandoc-1.15.2-1-amd64.deb

install:
  - bundle install

before_script:
  - cd vendor && npm install
  - cd ..

script:
  - bundle exec middleman build -e $RACK_ENV --verbose
  - bundle exec htmlproofer --http-status-ignore "999" --allow-hash-href --only-4xx ./build || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: $AWS_BUCKET
    region: eu-west-1
    skip_cleanup: true
    local_dir: build
    acl: public_read
    cache_control: "max-age=31536000"
    on:
      all_branches: true
  # - provider: s3
  #   access_key_id: $AWS_ACCESS_KEY
  #   secret_access_key: $AWS_SECRET_KEY
  #   bucket: $ARCHIVE_BUCKET
  #   region: eu-west-1
  #   skip_cleanup: true
  #   local_dir: source/posts
  #   upload-dir: blog
  #   acl: public_read
  #   cache_control: "max-age=31536000"
  #   on:
  #     all_branches: true

notifications:
  slack: $SLACK_TOKEN
  email: false

# after_deploy:
#   - bundle exec cirneco doi $CIRNECO_CMD https://${AWS_BUCKET}
#
#   - git config --global user.email "${GIT_EMAIL}"
#   - git config --global user.name "${GIT_NAME}"
#   - git config --global push.default simple
#   - git remote add upstream https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/datacite/blog.git
#
#   - git add source/.
#   - if ! [ -z "$(git status --untracked-files=no --porcelain)" ]; then
#       git commit -m 'Committing files changed by cirneco';
#       git push upstream HEAD:$TRAVIS_BRANCH;
#     fi
